# Generated by Django 5.0 on 2024-05-29 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daysmodel',
            options={'verbose_name_plural': 'Days Number'},
        ),
        migrations.AlterField(
            model_name='daysmodel',
            name='numbers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BasiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], max_length=10)),
                ('deposite', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('numbers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubscriptionApp.daysmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
