# Generated by Django 5.0 on 2024-05-29 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0002_alter_daysmodel_options_alter_daysmodel_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasiceModel',
            new_name='PackageModel',
        ),
        migrations.AlterModelOptions(
            name='packagemodel',
            options={'verbose_name_plural': 'Packages'},
        ),
    ]
