# Generated by Django 5.0 on 2024-05-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0003_rename_basicemodel_packagemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagemodel',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
