# Generated by Django 5.0 on 2024-05-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubscriptionApp', '0004_alter_packagemodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagemodel',
            old_name='created',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='packagemodel',
            old_name='numbers',
            new_name='days',
        ),
        migrations.AddField(
            model_name='packagemodel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='deposite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
